services:
  app:
    build: .
    container_name: nest-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://root:Universe2000@@localhost:5432/urlshort'
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Universe2000@
      POSTGRES_DB: urlshort
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
