services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: urlshort
      MYSQL_USER: testusr
      MYSQL_PASSWORD: testpwd
      MYSQL_ROOT_PASSWORD: testroot
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  app:
    build: .
    container_name: nest-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'mysql://testusr:testpwd@db:3306/urlshort'
    depends_on:
      - db
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
